version: '3'

services:
  db:
    hostname: database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: z
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "8082:5432"
    networks:
      - sheria-network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dogojanja50@gmail.com
      PGADMIN_DEFAULT_PASSWORD: nifamilia2424
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8083:80"
    networks:
      - sheria-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

volumes:
  db-data:
  pgadmin-data:


networks:
  sheria-network:
    driver: bridge
